all:
  hosts:
    home-cluster-1:
      ansible_host: 172.18.0.1
      ansible_user: ubuntu
    home-cluster-2:
      ansible_host: 172.18.0.2
      ansible_user: ubuntu
    home-cluster-3:
      ansible_host: 172.18.0.3
      ansible_user: ubuntu

  children:
    controller:
      hosts:
        home-cluster-1:
        home-cluster-2:
        home-cluster-3: