all:
  hosts:
    home-cluster-1:
      ansible_host: vm1.home
      ansible_user: ubuntu
    home-cluster-2:
      ansible_host: vm2.home
      ansible_user: ubuntu
    home-cluster-3:
      ansible_host: vm3.home
      ansible_user: ubuntu

  children:
    controller:
      hosts:
        home-cluster-1:
        home-cluster-2:
        home-cluster-3: