- name: Prepare system
  become: true
  hosts: all
  roles:
    - prepare_system
  tags:
    - prepare_system

- name: Install CRI
  become: true
  hosts: all
  roles:
    - install_cri
  tags:
    - install_cri

- name: Install Kubernetes packages
  become: true
  hosts: all
  roles:
    - install_k8s_packages
  tags:
    - install_k8s_packages

- name: Init cluster
  become: true
  hosts: controller[0]
  roles:
    - init_cluster
  tags:
    - init_cluster

# - name: Join nodes
