- name: Prepare system
  become: true
  hosts: all
  roles:
    - prepare_system
  tags:
    - prepare_system

- name: Install CRI
  become: true
  hosts: all
  roles:
    - install_cri
  tags:
    - install_cri

- name: Install Kubernetes packages
  become: true
  hosts: all
  roles:
    - install_k8s_packages
  tags:
    - install_k8s_packages

- name: Install Helm
  become: true
  hosts: controller
  roles:
    - install_helm
  tags:
    - install_helm

- name: Init cluster
  become: true
  hosts: controller[0]
  roles:
    - init_cluster
  tags:
    - init_cluster

- name: Install Calico CNI
  become: true
  hosts: controller[0]
  roles:
    - install_calico
  tags:
    - install_calico

- name: Acquire join credentials
  become: true
  hosts: controller[0]
  roles:
    - acquire_join_credentials
  tags:
    - acquire_join_credentials

# - name: Join nodes
